from real_estate import *


property1 = Property(square_feet=100, beds = 3, baths = 1)
print("Testing a Property class")
if property1.square_feet == 100: print('Test 1: OK ')
if property1.num_bedrooms == 3: print('Test 2: OK')
if property1.num_baths == 1: print('Test 3: OK')
property1.display()
property2 = Property(**Property.prompt_init())
if property2.square_feet == '125': print('Test 4: OK')
if property2.num_bedrooms == "2": print('Test 5: OK')
if property2.num_baths == "4": print("Test 6: OK")
print("Testing class Property finished")


print("Testing Apartment class")
apartment1 = Apartment(balcony='no', laundry='coin', square_feet=125, beds = 4, baths=38)
if apartment1.balcony == 'no': print('Test 1 passed')
if apartment1.laundry == "coin": print("Test 2 passed")
if apartment1.property.square_feet == 125: print("Test 3 passed")
if apartment1.property.num_bedrooms == 4: print("Test 4 passed")
if apartment1.property.num_baths == 38: print("Test 5 passed")
apartment1.display()
apartment2 = Apartment(**Apartment.prompt_init())
if apartment2.balcony == 'yes': print('Test 6 passed')
if apartment2.laundry == "none": print("Test 7 passed")
if apartment2.property.square_feet == "120": print("Test 8 passed")
if apartment2.property.num_bedrooms == "40": print("Test 9 passed")
if apartment2.property.num_baths == "3": print("Test 10 passed")
print("Test finished")


print("Testing House class")
house1 = House(num_stories='38', garage="none", fenced="no", square_feet="125", beds = "4", baths="38")
if house1.num_stories == '38': print('Test 1 passed')
if house1.garage == "none": print("Test 2 passed")
if house1.property.square_feet == "125": print("Test 3 passed")
if house1.property.num_bedrooms == "4": print("Test 4 passed")
if house1.property.num_baths == "38": print("Test 5 passed")
if house1.fenced == "no": print("Test 6 passed")
house1.display()
house2 = House(**House.prompt_init())
if house2.num_stories == '3': print('Test 7 passed')
if house2.garage == "detached": print("Test 8 passed")
if house2.property.square_feet == "25": print("Test 9 passed")
if house2.property.num_bedrooms == "4": print("Test 10 passed")
if house2.property.num_baths == "8": print("Test 11 passed")
if house2.fenced == "no": print("Test 12 passed")
print('Testing finished')

print("Testing a Purchase class")
purchase1 = Purchase(price = "2K", taxes="3K")
if purchase1.price == "2K": print('Test 1 passed')
if purchase1.taxes == "3K": print('Test 2 passed')
purchase2 = Purchase(**Purchase.prompt_init())
if purchase2.price == "27": print('Test 3 passed')
if purchase2.taxes == "38": print('Test 4 passed')
print("Testing finished")

print("Testing Rental class")
rental1 = Rental(furnished='no', utilities = "rauta", rent = "35K")
if rental1.furnished == "no": print("Test 1 passed")
if rental1.utilities == "rauta": print("Test 2 passed")
if rental1.rent == "35K": print("Test 3 passed")
rental2 = Rental(**Rental.prompt_init())
if rental2.furnished == "yes": print("Test 4 passed")
if rental2.utilities == "t": print("Test 5 passed")
if rental2.rent == "5": print("Test 6 passed")
print("Testing finished")


agent1 = Agent()
for i in range(2):
    agent1.add_property()
agent1.display_biggest_purchase()

